# Default values for openvsx.

name: open-vsx-org
environment: production
namespace: open-vsx-org
host: open-vsx.org

replicaCount: 2
esReplicaCount: 3

image:
  repository: ghcr.io/eclipsefdn/openvsx-website
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 97e1417-99

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 2Gi
