name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  WEBSITE_TAG: ghcr.io/eclipse/openvsx-website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Yarn
      run: npm install --global yarn@1.*
    - uses: actions/checkout@v2
    - name: Set Image Version
      run: echo "IMAGE_VERSION=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
    - name: Build Frontend
      run: |
        yarn --cwd website
        yarn --cwd website build
    - name: Build Website Image
      run: docker build -t $WEBSITE_TAG:$IMAGE_VERSION .
    - name: Push Website Image
      run: |
        echo ${{ secrets.BOT_ACCESS_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker push $WEBSITE_TAG:$IMAGE_VERSION
      if: github.repository == 'eclipse/open-vsx.org' && github.ref == 'refs/heads/master'
