name: Sonar
on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  sonar:
    name: Sonar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
